### ISSUE TITLE
ninja v1.11.0 is out

### ISSUE THREAD

**Issue by jack1142** [scikit-build/ninja-python-distributions#124]
ninja v1.11.0 has been out for a little bit over a month:
https://github.com/ninja-build/ninja/releases/tag/v1.11.0

It seems that the PyPI is the package is behind on that and I'm just wondering if there are any blockers for this release or if it's just perhaps been missed. Or maybe it's neither and the maintainers didn't yet have time to release a new version which is fine as well, I was just hoping to get some information about that and mention the new release in case the maintainers actually didn't know it is out :)

**Comment by jcfr** [comment]
Thanks for the ping 🙏

We will work on updating the version available on PyPi

**Comment by henryiii** [comment]
In the past we've needed a custom Kitware fork. Not sure what patches were required, or if they've been upstreamed. That's why this has lagged sometimes. @jcfr do you know if that's still needed?

**Comment by mayeut** [comment]
1.11.1 has been released

**Comment by jcfr** [comment]
To follow up on this, the Kitware fork has been updated. See https://github.com/Kitware/ninja/releases/tag/v1.11.1.g95dee.kitware.jobserver-1 and thanks to @mayeut the corresponding ninja package has been released. See https://github.com/scikit-build/ninja-python-distributions/releases/tag/1.11.1 and https://pypi.org/project/ninja/1.11.1/
