### ISSUE TITLE
1.11.1 release seems broken (edit: fixed now)

### ISSUE THREAD

**Issue by lazka** [scikit-build/ninja-python-distributions#157]
The version released today fails when called like `ninja --version` and doesn't have a zero return code.

```console
$ ninja --version
1.11.1.git.kitware.jobserver-1
$ echo $? 
245
```

This makes for example meson fail which calls `ninja --version` to detect the ninja version.

```console
$ meson _build
The Meson build system
[...]
ERROR: Could not detect Ninja v1.8.2 or newer
```

This is on Ubuntu 22.04 using Python 3.10.7

**Comment by lazka** [comment]
Just calling `ninja` or `ninja --help` is also broken.

**Comment by mayeut** [comment]
Thanks for the report. Don't know how it passed all tests in the first place because the simple reproducer indeed shows the failure.
@henryiii, @jcfr, can one of you yank the release on PyPI please. I can't do that.

**Comment by henryiii** [comment]
I do not have manage permissions for either `cmake` or `ninja`. Only @jcfr or @thewtex. I really yank permissions matched release permissions.

**Comment by henryiii** [comment]
We should make sure we check the return code in the tests.

**Comment by henryiii** [comment]
If you run it without the Python wrapper, it's:
```console
root@87dda27e737d:/# usr/local/lib/python3.10/dist-packages/ninja/data/bin/ninja --version
1.11.1.git.kitware.jobserver-1
Segmentation fault
```

**Comment by henryiii** [comment]
I think I'll have a rebuild out for the 1.11.1 issue soon. Looks like ninja 1.11.1 isn't compatible with manylinux1. Though why is it passing tests? Anyway, manylinux2010 builds don't suffer the same problem, and I can upload 2010 builds to the same release. ;)

**Comment by eli-schwartz** [comment]
Isn't manylinux1 vs manylinux2010 just about which version of glibc and libstdc++ you build against? Seems bizarre that ninja would be *incompatible* with anything there.

**Comment by henryiii** [comment]
It's segfaulting. I locally rebuild both manylinux1 and 2010 versions, and only the manylinux1 segfaults. It seems to get prettied up a bit by the python subprocess call. I've uploaded a 2010 version, let's see if that helps - it shouldn't hurt anything, other than the tiny bit of wasted space.

It should have failed the tests, though I think those also run in a manylinux1 container.

**Comment by henryiii** [comment]
Reproduced in #254. The manylinux1 wheel works _in_ manylinux1, but not in newer OSs - that's weird, I thought GLIBC wasn't supposed to be able to do that. Anyway, that means we have the ideal situation: Working manylinux1 wheels on manylinux1, and manylinux2010 wheels everywhere else (unless you have really old pip, then, sorry, but not shipping manylinux1 would be about the same). The 1.11.1 release is saved! :)

**Comment by mayeut** [comment]
Thanks for the quick fix @henryiii.
All tests for wheels are indeed running inside the manylinux container used to build said wheel. This is one thing where multibuild differs from cibuildwheel and there might be something to be done but that's another topic for cibuildwheel.
I'll have a look at #158 once I get some understanding of what's going on (debugging through CI though so might be a bit slow)

**Comment by mayeut** [comment]
Here's the backtrace for the observed issue (rebuilt the wheel without stripping but still in Release mode because Debug mode does not fail...):
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
#0  0x0000000000000000 in ?? ()
#1  0x0000000000436052 in std::ctype<char>::_M_widen_init() const ()
#2  0x00000000004174fa in (anonymous namespace)::GuessParallelism() [clone .5562] ()
#3  0x000000000041850e in (anonymous namespace)::real_main(int, char**) [clone .6198] ()
#4  0x00000000004044f9 in main ()
```
The ninja built on manylinux1 works correctly on manylinux1, manylinux2010, manylinux2014, manylinux_2_24 & ubuntu18.04. It segfaults on manylinux_2_28, ubuntu20.04+

I don't know where is the actual bug (I think it could be either a devtoolset-2 bug or a generic libstdc++ bug).
In any case, another possible solution/workaround for this is to continue building on manylinux1 but statically link libstdc++.

**Comment by henryiii** [comment]
What's the size difference?

**Comment by mayeut** [comment]
> What's the size difference?

x86_64:
- 301 kB vs 144 kB for the wheel
- 753 kB vs 299 kB for the ninja binary
i686:
- 317 kB vs 155 kB for the wheel
- 768 kB vs 285 kB for the ninja binary

PS: we might want to do this on musllinux where wheels (that are grafting libstdc++) are around 700/750 kB

**Comment by lazka** [comment]
thanks!

**Comment by ibc** [comment]
So can I use ninja 1.11.1 or not? PR #159 fixing this issue was merged in Nov 26, 2022. However the available 1.11.1 version still dates from august 30, 2022: 
https://github.com/ninja-build/ninja/releases

**Comment by eli-schwartz** [comment]
This has nothing to do with ninja releases.

It has everything to do with an external binary package :) So what you care about is the dates for https://pypi.org/project/ninja/#files

**Comment by lazka** [comment]
and as pointed out here: https://github.com/scikit-build/ninja-python-distributions/issues/157#issuecomment-1304681148 a wheel for newer distros was uploaded, so this is "fixed" for any non-ancient distro.

**Comment by henryiii** [comment]
Yes, a wheel with static linking for old manylinuxes is the only thing that hasn't been uploaded, but no one seems to have cared about that yet, so we haven't made a post release.

**Comment by ibc** [comment]
Clear now, thanks a lot for explaining.
