### ISSUE TITLE
ninja 1.9.0 has been released

### ISSUE THREAD

**Issue by slurps-mad-rips** [scikit-build/ninja-python-distributions#16]
Hello!

I came to discover the other day that [ninja 1.9.0][1] was released on January 31st. The main site has not been updated and you wouldn't know a release had taken place *unless* someone had gone to check. I figured I'd let someone know, as the latest release brings better performance from CMake and also ANSI color output support on Windows 🙂.

Thank you!

[1]: https://github.com/ninja-build/ninja/releases/tag/v1.9.0

**Comment by jcfr** [comment]
Thanks Isabella, we will create a new python package next week at the
earliest.

Best,
Jc

**Comment by jcfr** [comment]
Apologize for the delay, new package will be available as soon as we are done integrating #17

**Comment by jcfr** [comment]
For reference, see https://github.com/scikit-build/ninja-python-distributions/releases/tag/1.9.0

**Comment by jcfr** [comment]
Closing. Release in progress. See https://github.com/scikit-build/ninja-python-distributions/releases/tag/1.9.0 and https://pypi.org/project/ninja/1.9.0/#files

**Comment by slurps-mad-rips** [comment]
Thank you! :)
