### ISSUE TITLE
Trouble building on Raspberry PI 4

### ISSUE THREAD

**Issue by willm10034** [scikit-build/ninja-python-distributions#198]
I get the following error with whichever way I try to build...

cmake version 3.26.4
python version 3.11.3
(I've confirmed the same issue with python 3.11.4)

[89/402] BuildTest.WrongOutputInDepfileCausesRebuild
*** Failure in /home/pi/Downloads/ninja-python-distributions/Ninja-src/src/build_test.cc:574
build_res
[386/402] TokenPoolTest.IgnoreWithJNninja: warning: -jN forced on command line; ignoring GNU make jobserver.
[402/402] ElideMiddle.ElideInTheMiddle
failed
make[2]: *** [CMakeFiles/build_ninja.dir/build.make:120: build_ninja-prefix/src/build_ninja-stamp/build_ninja-run_ninja_test_suite] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/build_ninja.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Any help would be appreciated.

**Comment by willm10034** [comment]
This is fixed by using: python3 -m pip install ninja==1.10.0

**Comment by mayeut** [comment]
pip should now download a binary wheel.
