### ISSUE TITLE
Add Python 3.8 Wheels

### ISSUE THREAD

**Issue by thewtex** [scikit-build/ninja-python-distributions#20]
:xref: https://github.com/InsightSoftwareConsortium/ITK/pull/552

**Comment by jcfr** [comment]
* Update of dockcross manylinux images to include Python 3.8
  * [x] PR submitted to update manylinux base image. See https://github.com/pypa/manylinux/pull/273
  * [ ] PR integrated into https://github.com/pypa/manylinux and updated image published
  * [ ] Update of dockcross manylinux images

* Update of `ninja-python-distributions` CI configuration. See #21

**Comment by thewtex** [comment]
Updated manylinux dockcross images are now available!

-  https://github.com/dockcross/dockcross/commit/227d07ffdec91508046fd7aa88de49d83427afe8
-  https://hub.docker.com/r/dockcross/manylinux-x64/tags

**Comment by jcfr** [comment]
Closing. ABI independent wheels are being generated, see https://github.com/scikit-build/ninja-python-distributions/pull/21#issuecomment-496089053
