### ISSUE TITLE
`pip check` fails on amd64 linux and macOS

### ISSUE THREAD

**Issue by drewbrew** [scikit-build/ninja-python-distributions#256]
👋🏼 Hi, it looks like pip 24.2 causes ninja to register as incompatible with my local OS due to something in the package's metadata tags.

Environments tested (all amd64):

- Python 3.9 through 3.12 on WSL2 (Ubuntu 22.04 LTS)
- Python 3.9 on GitHub Actions runners (both Ubuntu 22.04 and 24.04)
- Python 3.9 on macOS

Steps to replicate:

1. Create a new virtualenv (`python3.12 -m venv .venv`)
2. `pip install --upgrade pip`
3. `pip install ninja`
4. `pip check`

Expected behavior:
- Output saying there are no package conflicts found

Actual behavior:
- `ninja 1.11.1.1 is not supported on this platform`

**Comment by yifanmai** [comment]
I'm running into this error as well on GitHub Actions with Ubuntu 22.04.4 LTS, Python 3.8.18 or 3.10.14, and pip 24.2.

I'm able to work around this error by downgrading pip to 24.1.2.

**Comment by drewbrew** [comment]
A coworker confirmed that macOS on ARM is also affected, and downgrading pip to 24.1.2 does indeed work around it.

**Comment by filbranden** [comment]
See pypa/pip#12884 for the root of the issue.

The current wheel for ninja 1.11.1.1 includes a blank line in the WHEEL file which makes the pip check break.

Can we get a new release of ninja that fixes the contents of WHEEL metadata to get this fixed? Thanks!

**Comment by mayeut** [comment]
Should be fixed in 1.11.1.2
