### ISSUE TITLE
 Missing release ninja 1.10 on pypi

### ISSUE THREAD

**Issue by priv-kweihmann** [scikit-build/ninja-python-distributions#29]
According to https://pypi.org/project/ninja/#history 1.9.0post1 (whatever that version might be) is the latest available version - are there any plans to dump a package to pypi soon?

I was referred here from https://github.com/ninja-build/ninja/issues/1754

**Comment by priv-kweihmann** [comment]
Nevermind - Just saw that you pulling sources while compiling, which is a clear no-go for me - went back to a different provider for ninja sources.
BTW you should really think about making it obvious that the pypi package isn't delivered by the actual project (but just my 2 cents)

**Comment by jcfr** [comment]
>BTW you should really think about making it obvious that the pypi package isn't delivered by the actual project (but just my 2 cents)

Good point. Would you mind submitting a pull request to update [README.rst](https://github.com/scikit-build/ninja-python-distributions/blob/master/README.rst). Since the rEADME.rst is displayed in both PyPI and GitHub, would that be enough ?

**Comment by jcfr** [comment]
>Nevermind - Just saw that you pulling sources while compiling, which is a clear no-go for me - went back to a different provider for ninja sources.

Since the goal of this project is to provide python wheel, you should definitively grab the source of ninja from the upstream repo. See https://github.com/ninja-build/ninja

**Comment by jcfr** [comment]
For reference, instructions to update the ninja version and make a release are available in the documentation. See https://github.com/scikit-build/ninja-python-distributions#maintainers

**Comment by priv-kweihmann** [comment]
> > BTW you should really think about making it obvious that the pypi package isn't delivered by the actual project (but just my 2 cents)
> 
> Good point. Would you mind submitting a pull request to update [README.rst](https://github.com/scikit-build/ninja-python-distributions/blob/master/README.rst). Since the rEADME.rst is displayed in both PyPI and GitHub, would that be enough ?

I don't know, my feeling is that there will still be much confusion, that the pypi version isn't created by the actual project and isn't really based on their release code.
Best solution would be to rename the pypi project and let the ninja project create their own releases to pypi.
Most users I know don't even read the README on pypi as they are just using pip - and in case something is buggy are blaming the wrong project.

Also I have to say, that the links in the setup.py shouldn't point to ninja, but somewhere around here.

Sure I could update README and setup.py but the question of the pypi project name remains.

**Comment by jcfr** [comment]
Waiting issue https://github.com/scikit-build/ninja-python-distributions/issues/33 is sorted out, I deleted the windows wheels from the latest 1.10.0 release. Thanks for understanding.

**Comment by jcfr** [comment]
![image](https://user-images.githubusercontent.com/219043/84442700-234c2800-ac0c-11ea-8c35-dac849c1abd9.png)
