### ISSUE TITLE
Add macOS arm64 or universal2 wheels

### ISSUE THREAD

**Issue by thewtex** [scikit-build/ninja-python-distributions#41]
xref https://github.com/scikit-build/cmake-python-distributions/issues/132

**Comment by henryiii** [comment]
@mayeut will you have time to to do this? Or should I plan to work on it in the future? We could also move to cibuildwheel, I think.

**Comment by mayeut** [comment]
As of now, I've just been looking how to upgrade the ninja version and there's one question which comes to my mind @jcfr probably has answer to:
I see that the upstream ninja repo now provides a universal2 binary however, this repo uses the Kitware fork to provide the make-style jobserver support.

I see multiple options and would like to know which one is appropriate:
- update with upstream 1.10.2
- Ask Kitware to release a 1.10.2 with make-style jobserver support and a universal binary.
- rebuild from current sources

If the answer is to build from sources, I'll have no way to test universal2 (no way to test in other cases as well but I'd rely on upstream or Kitware testing their released artifacts).

**Comment by jcfr** [comment]
Thanks for the derailed summary. 

I ask the CMake team to publish arm64 binaries. Will update this issue when I hear back.

**Comment by henryiii** [comment]
I've got an M1 and am happy to test if you need me to.

**Comment by jcfr** [comment]
> Will update this issue when I hear back.

It turns out we (aka colleagues working on CMake and VTK) are working this.
See https://gitlab.kitware.com/utils/ci-utilities/-/merge_requests/11

> I've got an M1 and am happy to test if you need me to.

That is great.

@mathstuf and bradking: If needed, @henryiii offered to help test.

**Comment by mayeut** [comment]
> It turns out my colleagues are working on this.

great news.

> I've got an M1 and am happy to test if you need me to.

Thanks @henryiii, have you been able to test cmake ? (I wouldn't expect any issues)

> will you have time to to do this? Or should I plan to work on it in the future? We could also move to cibuildwheel, I think.

I can prepare the same work as is being done on cmake to move to cibuildwheel.

**Comment by henryiii** [comment]
> have you been able to test cmake

Yes, just a very basic install and `--help` so far, but that worked fine.

**Comment by henryiii** [comment]
Looks like the linked MR was merged two weeks ago. What's the status for a release we can package (not sure where to find that in the repo)?

**Comment by mayeut** [comment]
> What's the status for a release we can package (not sure where to find that in the repo)?

I can see the tag in the Kitware repo but there's no release and no binary assets associated with that tag: https://github.com/Kitware/ninja/releases/tag/v1.10.2.g51db2.kitware.jobserver-1

@jcfr, can you check with your colleagues about that please ?

**Comment by mathstuf** [comment]
Binaries are available here: https://gitlab.kitware.com/utils/ci-utilities/-/releases/ninja%252Fv1.10.2.g51db2.kitware.jobserver-1

We already have gitlab-ci set up with access to macOS and Windows machines which seems to still be difficult on GitHub actions, so we just reused that infrastructure.

**Comment by mayeut** [comment]
Thanks for the links @mathstuf 

FYI, the Windows archive returns a 404 not found error on my end.

Given we're already building from source for almost all architectures and that the build seems much simpler than the one for CMake (and also much shorter), I wonder if we would be better off building everything from sources (using cmake rather than python bootstrap as is done in Kitware CI and also upstream CI) ? I will draft something for this. The only gotcha is that it might require to wait for a new release of scikit-build or some clever tricks for universal2 if going this way ?

**Comment by mathstuf** [comment]
> FYI, the Windows archive returns a 404 not found error on my end.

Hmm. Somehow the Windows binary got missed in the upload glob? I'll look at that next week.

**Comment by mayeut** [comment]
fixed by #63
