### ISSUE TITLE
Should cmake be listed as a dependency in pyproject.toml ?

### ISSUE THREAD

**Issue by mayeut** [scikit-build/ninja-python-distributions#44]
https://github.com/scikit-build/ninja-python-distributions/blob/98c811f31eb072756fe8f8c308a0bf936b030979/pyproject.toml#L2

I used this dependency to fix the SDist test in #43 but on second thought, it's not strictly required. CMake is required but if it's already on the system, then adding this might cause more harm than good ? (e.g. on alpine)

**Comment by henryiii** [comment]
I think we have to break the cycle somewhere, so probably yes, this should not be included?
