### ISSUE TITLE
Incorrect version of Ninja installed using PIP on M1

### ISSUE THREAD

**Issue by nazar-pc** [scikit-build/ninja-python-distributions#88]
Initially reported in https://github.com/ninja-build/ninja/issues/2049

On Mac when using ARM CPU the binary installed with PIP contains x86-64 executable instead of arm64.

Initially discovered in conjunction with Meson build system in https://github.com/versatica/mediasoup/issues/706 and can be tested by cloning that repo and doing `npm i` on Mac machine with M1 processor.

**Comment by mayeut** [comment]
The universal2 build seems to be broken since #70 (marked as universal2 but only contains an x86-64 binary).
Will provide a PR to fix this.
